### PR TITLE
Normalizing the representation of missig/null metadata

### LINKED ISSUE #585: inconsistent representation of missing/null metadata
If a BIOM JSON file is missing metadata along an axis, it is represented as `None`. With BIOM HDF5, missing metadata is represented as an empty `defaultdict`.

For example, I generated a file in QIIME in both formats using `summarize_taxa.py`. The following output differs when running `biom summarize-table` on both tables:

JSON:

```
...
Sample Metadata Categories: None provided
Observation Metadata Categories: None provided
...
```

HDF5:

```
...
Sample Metadata Categories:
Observation Metadata Categories:
...
```

Loading both tables into memory yields objects that are not equal due to different null metadata:

```python
In [1]: from biom import load_table

In [2]: t1 = load_table('qiime_overview_tutorial/taxa_summary/otu_table_L3.biom') # JSON

In [3]: t2 = load_table('h5py_qiime_tutorial/qiime_overview_tutorial/taxa_summary/otu_table_L3.biom') # HDF5

In [4]: t1 == t2
Out[4]: False

In [5]: t1.descriptive_equality(t2)
Out[5]: 'Observation metadata are not the same'

In [6]: t1.metadata(axis='observation')

In [7]: t2.metadata(axis='observation')
Out[7]:
(defaultdict(<function <lambda> at 0x10e7098c0>, {}),
 defaultdict(<function <lambda> at 0x10e709938>, {}),
 defaultdict(<function <lambda> at 0x10e7099b0>, {}),
 defaultdict(<function <lambda> at 0x10e709a28>, {}),
 defaultdict(<function <lambda> at 0x10e709aa0>, {}),
 defaultdict(<function <lambda> at 0x10e709b18>, {}),
 defaultdict(<function <lambda> at 0x10e709b90>, {}),
 defaultdict(<function <lambda> at 0x10e709c08>, {}),
 defaultdict(<function <lambda> at 0x10e709c80>, {}),
 defaultdict(<function <lambda> at 0x10e709cf8>, {}),
 defaultdict(<function <lambda> at 0x10e709d70>, {}),
 defaultdict(<function <lambda> at 0x10e709de8>, {}),
 defaultdict(<function <lambda> at 0x10e709e60>, {}))
```

### PR DESCRIPTION
**Pull request by josenavas**
Fixes #585 

Sorry for the delay on this. It turns out it was a pretty easy fix, I just needed to find the time to check where was the issue originated.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Looks good, but can you add a unit test for this? Though I don't know if
it's possible.

**Comment by josenavas** [comment]
Tests added. Thanks @ElDeveloper

**Comment by Jorge-C** [comment]
A build failed (without looking into it too much it is stochastic), and another one didn't finish because of a network problem. Can someone retest that please?

**Comment by ElDeveloper** [comment]
Restarted, tested this in my system and it seems to be working just
fine.

**Comment by ElDeveloper** [comment]
:+1:

**Comment by josenavas** [comment]
Thanks!

**Pull request merged**
