### PR TITLE
converting biom convert to be click-based

### PR DESCRIPTION
**Pull request by gregcaporaso**
still some items to-do - moved those to #631.

### CODE REVIEW

**Comment by wasade** [comment]
:+1: so far

**Comment by gregcaporaso** [comment]
@wasade, note one change that you may have missed: I added a new table type, ``Table``, which is the default. This makes ``--table-type`` no longer required. Since this field is never used (to the best of my knowledge) forcing users to specify it has just become annoying. This doesn't break backward compatibility. Any issues with this?

**Comment by wasade** [comment]
Seems okay as the types really aren't used to the best of my knowledge

**Comment by ebolyen** [comment]
flake8 error, if this gets merged I can update #666

**Comment by gregcaporaso** [comment]
flake8 error should be fixed. @ebolyen, there are still some things I need to do on this one, but if you're going to work on #666 tonight you can merge this and I can take care of those items in a new PR tomorrow. I gave you write access to the repo.

**Comment by ebolyen** [comment]
Thanks @gregcaporaso, I'll merge this once tests pass and then update my PR

**Comment by gregcaporaso** [comment]
Thanks! I moved my to-do items to #631.

**Pull request merged**
