### PR TITLE
BUG/ENH: Check for filesize when reading file

### LINKED ISSUE #614: Empty file causes non-informative error
Trying to load an empty file, yields a rather non-informattive error, it would be really nice if a more informative error was raised instead, though I understand if this is out of the scope of the parsers.

To reproduce in your machine try the following:

```
(qiime-dev)yoshikivazquezbaeza:16s$ touch lolercoaster.biom # this file didn't exist
(qiime-dev)yoshikivazquezbaeza:16s$ biom summarize-table -i lolercoaster.biom 
```

Which causes the following error:

```python
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/bin/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/pyqi/core/interface.py", line 38, in __call__
    cmd_input = self._input_handler(in_, *args, **kwargs)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 194, in _input_handler
    self._optparse_input[optparse_clean_name])
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/interfaces/optparse/input_handler.py", line 56, in load_biom_table_with_file_contents
    table = parse_biom_table(biom_f)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/parse.py", line 312, in parse_biom_table
    t = Table.from_tsv(fp, None, None, lambda x: x)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/table.py", line 3773, in from_tsv
    t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/table.py", line 3864, in _extract_data_from_tsv
    for index in range(0, data_start + 1):
UnboundLocalError: local variable 'data_start' referenced before assignment
```

-----

I've also been able to reproduce this using the `load_table` function only:

```python
In [1]: from biom import load_table

In [2]: bt = load_table('lolercoaster.biom')
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-2-ef8b4f2e225d> in <module>()
----> 1 bt = load_table('lolercoaster.biom')

/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/parse.pyc in load_table(f)
    549     with biom_open(f) as fp:
    550         try:
--> 551             table = parse_biom_table(fp)
    552         except (IndexError, TypeError):
    553             raise TypeError("%s does not appear to be a BIOM file!" % f)

/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/parse.pyc in parse_biom_table(fp, ids, axis, input_is_dense)
    310         else:
    311             fp.seek(old_pos)
--> 312             t = Table.from_tsv(fp, None, None, lambda x: x)
    313     elif isinstance(fp, list):
    314         try:

/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/table.pyc in from_tsv(lines, obs_mapping, sample_mapping, process_func, **kwargs)
   3771         """
   3772         (sample_ids, obs_ids, data, t_md,
-> 3773             t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
   3774 
   3775         # if we have it, keep it

/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/table.pyc in _extract_data_from_tsv(lines, delim, dtype, md_parse)
   3862         else:
   3863             lines.seek(0)
-> 3864             for index in range(0, data_start + 1):
   3865                 line = lines.readline()
   3866 

UnboundLocalError: local variable 'data_start' referenced before assignment
```

### PR DESCRIPTION
**Pull request by ElDeveloper**
Add an explicit check to verify the passed file is not empty.

Fixes #614

### CODE REVIEW

**Comment by Jorge-C** [comment]
There are two test failures when using h5py.

**Comment by ElDeveloper** [comment]
Thanks for the heads-up, I'll look into it.

**Comment by ElDeveloper** [comment]
Ok, should be fixed now.

**Comment by Jorge-C** [comment]
:+1:

**Comment by wasade** [comment]
Thanks @ElDeveloper!!

**Comment by ElDeveloper** [comment]
:boom:

**Pull request merged**
