### PR TITLE
620

### PR DESCRIPTION
**Pull request by Jorge-C**
@wasade I changed the error checking in the `filter` method so that in #620 the error would have been raised just after filtering, instead of at a later stage when sorting. Can you please check that it's fine? Thanks!

### CODE REVIEW

**Comment by Jorge-C** [comment]
Hey, I've set coveralls to fail only if coverage decreases by more than 5% or below 70%. Feel free to tweak the numbers, but it's silly that we are seing build failures because a covered line was removed and that decreases coverage by 0.0001%  :)

**Comment by wasade** [comment]
Agree, thanks!

Reviewing now. Please do add a changelog mention when you get a second

**Comment by wasade** [comment]
This seems good, thanks! Just need the changelog mention and will merge

**Comment by Jorge-C** [comment]
Thanks @wasade, changelog edited.

**Pull request merged**
