### PR TITLE
IDs via the CLI

### PR DESCRIPTION
**Pull request by wasade**
A quick one. We do not currently exercise the CLI directly in other places, and this is a really minimal wrapper, so I'm hoping this is just acceptable as is.

### CODE REVIEW

**Comment by mortonjt** [comment]
This is great.  What do you think about opening up a separate issue/PR for dumping metadata?

**Comment by mortonjt** [comment]
Although, I'm having a very difficult time trying to run this command.  Could you print out the help menu, just so we can confirm that it is working?

**Comment by wasade** [comment]
re: metadata, that is not straight forward. I'm not sure if I'd like to hold up 2.1.6 for it.

```bash
$ biom table-ids --help
Usage: biom table-ids [OPTIONS]

  Dump IDs in a table.

  Dump out the IDs found within a table/

  Example usage:

  Get the sample IDs within a table:

  $ biom table-ids -i table.biom

  Get the observation IDs within a table:

  $ biom table-ids -i table.biom --observations

Options:
  -i, --input-fp PATH  The input BIOM table  [required]
  --observations       Grab observation IDs
  -h, --help           Show this message and exit.
$ biom table-ids -i examples/min_sparse_otu_table.biom
Sample1
Sample2
Sample3
Sample4
Sample5
Sample6
$ biom table-ids -i examples/min_sparse_otu_table.biom --observations
GG_OTU_1
GG_OTU_2
GG_OTU_3
GG_OTU_4
GG_OTU_5
```

**Comment by wasade** [comment]
@mortonjt, see #740

**Pull request merged**
