### PR TITLE
Issue 731

### PR DESCRIPTION
**Pull request by wasade**
Resolves issue #731. Should be a quick review. We weren't enforcing a conversion from bytes to non-bytes for a few attributes.

### CODE REVIEW

**Comment by antgonza** [comment]
what happened with the coverage?

**Comment by wasade** [comment]
Might be due to the py27 failure. I hate python2.

**Comment by wasade** [comment]
More travis issues? Doesn't look like the build was triggered at all

**Comment by wasade** [comment]
Ya. Travis is reporting a partial system outage due to a major impact to Heroku. Lame.

**Comment by wasade** [comment]
@antgonza we're green. I'm pushing in a changelog bugfix mention but other than that, I believe were good to go

**Pull request merged**
