### PR TITLE
Fix595

### LINKED ISSUE #595: BIOM convert is not recording version information correctly
If you convert an HDF5 table (format 2.1.0) to JSON, the resulting file format indicates it is 2.1.0.

```bash
(python27)12:29:55 examples@master$ biom convert -i min_sparse_otu_table_hdf5.biom -o foo --to-json
(python27)12:30:15 examples@master$ cut -c 1-80 foo
{"id": "No Table ID","format": "Biological Observation Matrix 2.1.0","format_url
```

This is incorrect as the JSON file format is actually version 1.0.0.

### PR DESCRIPTION
**Pull request by Jorge-C**
Any ideas on how to add a test for this?

Fixes #595.

### CODE REVIEW

**Comment by wasade** [comment]
Not worth it imo, mergable?

**Comment by adamrp** [comment]
I don't think it requires a test, either, but looking at the code does raise one question. Do we want to record the code version as well as the format version? That way, we know this is biom *format* 1.0 that was written with X version of the code (might make it easier to track bugs in the future).

**Comment by wasade** [comment]
We'd need to redefine both BIOM-Format 1.0 and 2.0

**Comment by Jorge-C** [comment]
Then it's already mergable.

**Pull request merged**
