### PR TITLE
Fixed #745

### LINKED ISSUE #745: Conversion to hdf5 from json_biom
There seems to be an error when converting json biom files (created by MetaPhlAn2) into the hdf5 format.
Setup: python 3.5 on Linux workstation
Repository version: 32182413626ee729507a52cb2d33708978713129 (most recent at time of writing)
Example:
```
somefile.biom.json:
{
  "id": "MetaPhlAn2_Analysis",
  "format": "Biological Observation Matrix 1.0.0",
  "format_url": "http:\/\/biom-format.org",
  "generated_by": "MetaPhlAn2",
  "date": "2017-04-13T20:02:41.706093",
  "matrix_element_type": "float",
  "shape": [
    1,
    1
  ],
  "type": null,
  "matrix_type": "sparse",
  "data": [
    [
      0,
      0,
      100
    ]
  ],
  "rows": [
    {
      "id": 468,
      "metadata": {
        "taxonomy": [
          "k__Bacteria",
          "p__Actinobacteria",
          "c__Actinobacteria",
          "o__Bifidobacteriales",
          "f__Bifidobacteriaceae",
          "g__Bifidobacterium",
          "s__Bifidobacterium_breve"
        ]
      }
    }
  ],
  "columns": [
    {
      "id": "Metaphlan2_Analysis",
      "metadata": null
    }
  ]
}

Command:
biom convert -i somefile.biom.json -o somefile.biom --to-hdf5
Traceback (most recent call last):
  File "***/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "***/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "***/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "***/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "***/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "***/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "***/lib/python3.5/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "***/lib/python3.5/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "***/lib/python3.5/site-packages/biom/cli/util.py", line 35, in write_biom_table
    table.to_hdf5(f, biom.parse.generatedby())
  File "***/lib/python3.5/site-packages/biom/table.py", line 4119, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "***/lib/python3.5/site-packages/biom/table.py", line 4071, in axis_dump
    data=[i.encode('utf8') for i in ids],
  File "***/lib/python3.5/site-packages/biom/table.py", line 4071, in <listcomp>
    data=[i.encode('utf8') for i in ids],
AttributeError: 'int' object has no attribute 'encode'
```

It seems as if the to_hdf5 function assumes the ids to be strings, while MetaPhlAn encodes them as integer types in the json file.

### PR DESCRIPTION
**Pull request by maexlich**

### CODE REVIEW

**Comment by wasade** [comment]
The IDs are defined as strings already, so this PR would allow malformed tables to be expressed.

As a stop-gap for #745, one thing which should work is:

```python
>>> table = biom.load_table(foo)  # this _should_ tolerate integer IDs in BIOM-format 1.0.0
>>> table = biom.Table(table.matrix_data, [str(i) for i in table.ids(axis='observation')], [str(i) for i in table.ids()], table.metadata(axis='observation'), table.metadata())
>>> with h5py.File(bar, 'w') as fp:
    table.to_hdf5(bar, 'converted')
```

**Comment by SilviaRaineri** [comment]
Hello! 

I am currently having this issue with my Metaphlan2 biom table (ie. I cannot load it into R for further analysis). I tried the code suggested by wasade, but it keeps giving me an error:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/bioc1484/miniconda3/lib/python3.6/site-packages/biom/table.py", line 4105, in to_hdf5
    h5grp.attrs['id'] = self.table_id if self.table_id else "No Table ID"
AttributeError: 'str' object has no attribute 'attrs'


My code looks like this:
import biom
import h5py
from biom import load_table
table = biom.load_table('trialA12.biom')  # this _should_ tolerate integer IDs in BIOM-format 1.0.0
table = biom.Table(table.matrix_data, [str(i) for i in table.ids(axis='observation')], [str(i) for i in table.ids()], table.metadata(axis='observation'), table.metadata())

with h5py.File('trialA12_h5.biom', 'w') as fp:
    table.to_hdf5('trialA12_h5.biom', 'converted')

I also tried simply doing a biom convert on the original biom table  using  maexlich #745 biom-format version, but once I load that hdf5 into R the table is malformed (as stated by wasade). Can anyone help?

Silvia

**Comment by wasade** [comment]
It looks like there was a typo in my untested example: "table.to_hdf5('trialA12_h5.biom', 'converted')" should be "table.to_hdf5(fp, 'converted')". However, I strongly recommend filing a bug report with metaphlan2 as they are producing invalid tables.

**Comment by SilviaRaineri** [comment]
Thanks for your help, I will file it now.

**Comment by maexlich** [comment]
There already exists an issue for quite some time now: https://bitbucket.org/biobakery/metaphlan2/issues/35/incompatibility-of-biom-output-with-biom
And there seem to be more and more accumulating...

The metaphlan2 people don't seem very responsive. Also they disabled the possibility to open pull requests...

Generally I would not recommend to take the biom output of metaphlan seriously, the output is not reproducible at all (OTU IDs for same species change in between runs making it impossible to use the tables with qiime (especially merge tables)). I will fork there repo on bitbucket soon providing a bugfix on theses problems. (More information see here: https://bitbucket.org/biobakery/metaphlan2/issues/38/otu-ids-in-between-runs-are-not)

**Comment by SilviaRaineri** [comment]
Thanks, I have both commented on the thread in issue 35 and started a new one (hadn't seen issue 35 beforehand). At this point, I will try to use the txt table to do the first preliminary analyses on R while I wait for this problem to be solved...

**Comment by wasade** [comment]
That is unfortunate and annoying, thank you for the heads up @maexlich and thank you both for following up with them. 

BIOM-Format version 1.0.0 (the JSON-based representation) unambiguously defines the IDs as being strings. Accommodating these tables would require a new format spec, which would still require changes in metaphlan2 as they would, at a minimum, need to modify the format version they record in the file output. The path of least resistance is for that project to produce tables within spec.

**Comment by wasade** [comment]
I made a brief follow up post on the metaphlan2 tracker as well.

**Comment by george-weingart** [comment]
I am looking into the problem of Metaphlan2 not generating correct Biom output .
BIOM 1.0 specifications state that “IDs should be  <string or null> a field that can be used to id a table (or null)”

I ran a Metaphlan2 test using the sample file:  https://bitbucket.org/biobakery/galaxy_metaphlan2/wiki/metaphlan2_synth_sample.fastq

and got the results that look like:

"rows": [{"id": "1445", "metadata": {"taxonomy": ["k__Archaea", "p__Euryarchaeota", "c__Thermoplasmata", "o__Thermoplasmatales", "f__Ferroplasmaceae", "g__Ferroplasma", "s__Ferroplasma_acidarmanus", "t__GCF_000152265"]}},}........


 I ran biom validate-table against the output biom file and it was successful.

[george.weingart@hutlab3 metaphlan2]$ biom validate-table -i results1.biom
The input file is a valid BIOM-formatted file.

So in order to solve the problem on our side and modify the metaphlan2 code,  can I ask members of the forum that reported the issue to send me an example of an input file to metaphlan2 where they encountered the problem and a description of how they ran metaphlan2  ?

Thanks!
George Weingart PhD
Huttenhower Lab
george.weingart@gmail.com

**Comment by SilviaRaineri** [comment]
Hello, 
I am having trouble in loading the biom file into R for further analysis. Here's what I tried so far:
In R:
```
library(biomformat)
A12 <- read_biom('A12b.biom')
```
Output: Error in if (!object$type %in% biomtypevals) { :  argument is of length zero

If I try to convert it into hdf5 using this code:
`biom convert -i A12b.biom -o A12b_hdf5.biom --to-hdf5`
This happens:
```
Traceback (most recent call last):
  File "/home/bioc1484/miniconda3/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/biom/cli/util.py", line 35, in write_biom_table
    table.to_hdf5(f, biom.parse.generatedby())
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/biom/table.py", line 4123, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/home/bioc1484/miniconda3/lib/python2.7/site-packages/biom/table.py", line 4075, in axis_dump
    data=[i.encode('utf8') for i in ids],
AttributeError: 'int' object has no attribute 'encode'
```
Please find attached 
a12b biom
the biom table. 

I can't figure out whether on top of the biom format being a bit weird with Metaphlan2 output I am also doing something wrong.

**Comment by maexlich** [comment]
Hey George,

can we move this discussion to the bitbucket issue?
I will provide a reproducibility example there soon.
But nevertheless some specs: We are running metaphlan2 with python 3.5 and the most recent version of the biom-format package.
Looking at the lines 1035&1036 and 1049&1060 of metaphlan2.py, integers are being passed to either table_factory or the Table constructor. I don't really understand why your results are in the correct format.

**Comment by george-weingart** [comment]
We implemented a change in metaphlan2.py today to use the clade name as identifier instead of the clade id, which looks numeric.
The new table will have entries that look like:
 
{"id": "k__Archaea|p__Euryarchaeota|c__Thermoplasmata|o__Thermoplasmatales|f__Ferroplasmaceae|g__Ferroplasma|s__Ferroplasma_acidarmanus|t__GCF_000152265", "metadata": {"taxonomy": ["k__Archaea", "p__Euryarchaeota", "c__Thermoplasmata", "o__Thermoplasmatales", "f__Ferroplasmaceae", "g__Ferroplasma", "s__Ferroplasma_acidarmanus", "t__GCF_000152265"]}}
 
Instead of the old entries that look like: 
 
{"id": "1445", "metadata": {"taxonomy": ["k__Archaea", "p__Euryarchaeota", "c__Thermoplasmata", "o__Thermoplasmatales", "f__Ferroplasmaceae", "g__Ferroplasma", "s__Ferroplasma_acidarmanus", "t__GCF_000152265"]}
   
Checked the new format passes “biom validate-table”  and was able to load the biom output file to R using library(BIOM.utils).
 
Using the clade names  will make sure the identifiers do not change from run to run for the same data.
 
The change is available at Biobakery: https://bitbucket.org/biobakery/metaphlan2
 
Galaxy Users:  Please note the change will be implemented next time we recycle the server.
I will notify this forum when this will happen.
 
Please let me know if you have any questions.
 
George Weingart PhD
Huttenhower Lab

**Comment by george-weingart** [comment]
Galaxy Users: Please note the change has been implemented for Metaphlan2 in Galaxy: http://huttenhower.sph.harvard.edu/galaxy/

Please let me know if you have any questions.

George Weingart PhD
Huttenhower Lab

**Pull request closed without merging**
