### PR TITLE
Rapid subset

### PR DESCRIPTION
**Pull request by wasade**
@josenavas, possible for a review on this? Asking as I believe you wrote the normal subset method. Basically, the subset kills you when handling metadata, which is fine for one-off runs, but I need to do repeated subsetting for EMP in the context of the block decomposition for unifrac. See [here](https://gist.github.com/wasade/60db4059e3b7e42bb648db1d10ef72d6) for the motivator, which I'd like to get running tomorrow on EMP oref. This PR doesn't block, but it's necessary for this approach to be feasible

### CODE REVIEW

**Comment by josenavas** [comment]
Code looks good. I see in your commit history that you decided not to filter zero'd rows/cols, why was it beneficial for block decomp unifrac? I was gonna suggest adding it but if there is a good argument against it I'm fine with it :-)

**Comment by wasade** [comment]
Code assumes subset is in index order with full table. Difficult to work
around right now as the skbio API takes a dense numpy matrix for counts so
no index labels

**Comment by josenavas** [comment]
ooooh makes sense! Thanks @wasade

**Comment by gregcaporaso** [comment]
@wasade, @josenavas is the default behavior the same? Just wondering if this will require a version bump to maintain backward compatibility for QIIME and any other projects that depend on `` < 2.2.0``. Thanks!

**Comment by wasade** [comment]
Yes

**Comment by gregcaporaso** [comment]
Thanks!

**Pull request merged**
