### PR TITLE
utf8 files in PY2

### PR DESCRIPTION
**Pull request by Jorge-C**
Read biom files as if they were utf8 in PY2 (closes issue #690, but not ready for merge yet).

It just changes a few lines of code, and declares all biom text files to be encoded as utf-8 (a parameter could potentially be provided to change that).

However, it needs testing work (adding/fixing some), so please feel free to grab it and get it ready for merge in the next few days. Otherwise I'll work on it sometime next week.

Rationale for changes:
- io.open is open in PY3, and is the cleanest way to get PY3's behaviour in PY2.
- Gzipped files are trickier (they provide an encoding argument in PY3!), and it
  seems using the codecs module is the way to go [1, 2], but it needs more testing...

[1] https://docs.python.org/2/howto/unicode.html
[2] http://stackoverflow.com/a/1883734/1191119

### CODE REVIEW

**Comment by wasade** [comment]
Hey @Jorge-C, any chance this PR can be finalized?

**Comment by Jorge-C** [comment]
I'll take a look Daniel! What's your timeline?

**Comment by wasade** [comment]
Nothing particular... :)

**Comment by Jorge-C** [comment]
Added some tests to make sure the behaviour keeps being right in the future.

There's a test that uses `isinstance` to check that open_biom('foo.gz') returns a  `gzip.GzipFile`. To support utf-8 in py2 I need to return another duck that quacks like it... What are your thoughts about deleting that `isinstance` check?

**Comment by wasade** [comment]
Am fine with dropping the `isinstance`. It looks like there are some failures btw

**Comment by Jorge-C** [comment]
Yeah, the only failure was that test that used `isinstance`. This is ready now.

**Pull request merged**
