### PR TITLE
Explicitly allow setting a random seed for subsample

### LINKED ISSUE #914: Setting a random seed
Documentation and a verifiable example of setting a random seed should be provided.

### PR DESCRIPTION
**Pull request by wasade**
Fixes #914. You can now specify the random seed on call to `Table.subsample(...)`.

cc @gibsramen @rob-knight

### CODE REVIEW

**Comment by gibsramen** [comment]
Thanks, @wasade. How much work would it be to rewrite the random shuffling into the new NumPy random API? Setting seed with `np.random.seed` is now a [legacy function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html) that sets the *global* random seed which can have some unintended consequences. The new RNG documentation is [here](https://numpy.org/doc/stable/reference/random/index.html#random-sampling-numpy-random).

**Comment by wasade** [comment]
Good observation. Likely easy given the methods are there but the signature for the underlying cython method will need a minor adjustment

```
>>> from numpy.random import default_rng
>>> rng = default_rng(12345)
>>> rng.multinomial
<built-in method multinomial of numpy.random._generator.Generator object at 0x7f9c385c1900>
>>> rng.permutation
<built-in method permutation of numpy.random._generator.Generator object at 0x7f9c385c1900>
>>> 
```

**Comment by wasade** [comment]
@gibsramen if this is green can you merge?

**Comment by gibsramen** [comment]
Looks good, thanks! I think this is good to merge.

**Comment by wasade** [comment]
Thanks!

**Pull request merged**
