### PR TITLE
DOC: listing 2.1.4 changes

### PR DESCRIPTION
**Pull request by wasade**
One step closer to 2.1.4. We need to deploy and test against QIIME before the release is actually cut, marking as 2.1.4rc1 for now.

NOTE: version tags across the codebase have _not_ been updated. Will do that on release.

### CODE REVIEW

**Comment by Jorge-C** [comment]
Something odd is going on with the newest cython version (I can reproduce locally)

**Comment by gregcaporaso** [comment]
To test for QIIME, easiest might be to just boot up the latest VirtualBox or AWS instance, install this version of biom via ``sudo pip install http://....zip --upgrade`` and then run ``all_tests.py``.

**Comment by wasade** [comment]
@gregcaporaso, running on pando right now in essentially that though the install isn't a complete one. Good call on VB, will pull and boot

@Jorge-C, that is weird. Looks like cython got a little more picky over types that should be compatible AFAIK. Do you think you can push a fix in on it?

**Comment by Jorge-C** [comment]
Yes, I'm working on that right now!

**Comment by wasade** [comment]
Great, thanks!

Just remembered I'm on a home connection right now, so the 3.6GB download for the VM sucks, and I don't have any AWS creds at the moment. Will pull image once I get on campus

**Comment by gregcaporaso** [comment]
Oh... if you're pretty confident that this will work with QIIME, the
easiest is to just do a biom release, update the minimum dependency in
QIIME's setup.py, and issue a pull request. Jenkins will then pull that
version of biom and use it for testing.

Do I have all of that right @jairideout?

**Comment by jairideout** [comment]
That sounds right. Do we want to update the minimum required version in QIIME or keep it as-is? We didn't update the minimum required version for scikit-bio when we pushed a minor bug fix release.

Either way, issuing a PR like this will kick off the tests and allow us to see if there's any issues (we can always close it afterwards).

**Comment by gregcaporaso** [comment]
I was thinking we could just leave the same minimum version number, but just use this to kick off the tests. Though I guess updating the minimum in QIIME 1.9.0-dev doesn't hurt...

**Comment by wasade** [comment]
The downside is that we potentially cut a release that we then need to
backtrack, unless I'm misunderstanding?

**Comment by jairideout** [comment]
Good point, I guess we might as well update the minimum version for 1.9.0-dev (could do this for scikit-bio too).

**Comment by gregcaporaso** [comment]
@wasade, I don't understand your last question, sorry. Can you clarify?

**Comment by wasade** [comment]
@gregcaporaso, you're recommending that we just do the release and then test against qiime, right? Doesn't that expose us to the possibility of needing to retract the release if there is some aspect of 2.1.4 that is not qiime 1.9 compatible?

**Comment by gregcaporaso** [comment]
Got it. Definitely, I think it'd only be a good way to go if you're 99% sure that it works with QIIME, and just want to do a last test to confirm.

**Comment by wasade** [comment]
Will wait to pull down the VM and test directly :)

**Comment by Jorge-C** [comment]
Build is now green, this can be merged, right?

**Comment by wasade** [comment]
Unsure... I've got some test failures but many are due to an incomplete
install. investigating

**Comment by wasade** [comment]
Ya, I think the failures are all due to an incomplete install of qiime in
my environment. Need to test on a full install, which will be easiest on a
VM. I'll be heading to better internet somewhat soon

**Comment by wasade** [comment]
@gregcaporaso, shouldn't numpy be available immediately on the VM?
screen shot 2015-03-05 at 3 53 16 pm

**Comment by wasade** [comment]
...I tried executing `/qiime_software/activate.sh` but still no numpy...

**Comment by ElDeveloper** [comment]
I just tried in my VM and it works:

screen shot 2015-03-05 at 2 56 52 pm

**Comment by wasade** [comment]
I've got a fresh copy of 1.9 VM...
screen shot 2015-03-05 at 3 59 59 pm

**Comment by wasade** [comment]
Did coveralls change its reporting? I'm getting a -7% coverage but the report isn't showing any change.

**Comment by wasade** [comment]
somehow i hosed a fresh env... no idea how

**Comment by wasade** [comment]
Okay, got these. @gregcaporaso @jairideout, are these expected? No usearch in my environment. 
screen shot 2015-03-05 at 5 44 25 pm

**Comment by jairideout** [comment]
Those look like expected failures, @gregcaporaso do you agree? Probably the safest thing to do is scroll through the output and make sure the errors are only related to missing installs of usearch, torque, and sfffile/sffinfo.

**Comment by gregcaporaso** [comment]
That looks good, those are the usual failures from the missing apps that @jairideout mentioned. I do usually scroll through the full output just to confirm (we clearly need to be using conditional unit testing there... QIIME 2...).

**Comment by wasade** [comment]
I believe this is good to merge and release

**Comment by wasade** [comment]
Just an update on this, I'm still working through some issues for the biom 2.x update to picrust and it is possible this will trigger a few other changes to biom. I'd like to hold off release of 2.1.4 until the picrust is good to go

**Pull request merged**
